# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
  build:
    working_directory: ~/CircleCITest
    docker:
    -
      image: 'circleci/openjdk:8-jdk-stretch'
    steps:
      - checkout
      -
        restore_cache:
          key: 'junit5-examples-{{ checksum "pom.xml" }}'
      -
        run: 'mvn dependency:go-offline'
      -
        save_cache:
          paths:
            - ~/.m2
          key: 'junit5-examples-{{ checksum "pom.xml" }}'
      -
        run: 'mvn test -P first'
      -
        store_test_results:
          path: target/surefire-reports
      -
        store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
